apiVersion: v1
kind: Service
metadata:
  name: azurite-service
  namespace: ${namespace}
  labels:
    app: azurite
spec:
  selector:
    app: azurite
  type: ClusterIP
  ports:
  - name: blob
    port: 10000
    protocol: TCP
    targetPort: 10000
  