apiVersion: v1
kind: Service
metadata:
  name: {appName}-service
  namespace: ${namespace}
  labels:
    app: {appName}
spec:
  selector:
    app: {appName}
  type: ClusterIP
  ports:
  - name: tcp
    port: {portNumber}
    protocol: TCP
    targetPort: {portNumber}